name: Deploy
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GCP_DEPLOY_SERVICE_ACCOUNT: ${{ secrets.GCP_DEPLOY_SERVICE_ACCOUNT }}
  SERVICE_NAME: qrurl-app
  REGION: asia-northeast1

jobs:
  deploy:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}

    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v0.4.0"
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_DEPLOY_SERVICE_ACCOUNT }}@${{ secrets.GCP_PROJECT_ID }}.iam.gserviceaccount.com

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Deploy to Cloud Run
        run: |-
          echo "GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}" > .env.yaml
          echo "LINE_MESSAGE_CHANNEL_SECRET: ${{ secrets.LINE_MESSAGE_CHANNEL_SECRET }}" >> .env.yaml
          echo "LINE_PUBLIC_KEY_ID: ${{ secrets.LINE_PUBLIC_KEY_ID }}" >> .env.yaml
          echo "LINE_CHANNEL_ID: '${{ secrets.LINE_CHANNEL_ID }}'" >> .env.yaml
          echo "LINE_PRIVATE_KEY: ${{ secrets.LINE_PRIVATE_KEY }}" >> .env.yaml
          echo "LINE_CHANNEL_ACCESS_TOKEN: ${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}" >> .env.yaml
          gcloud run deploy $SERVICE_NAME \
            --project=$GCP_PROJECT_ID \
            --region=$REGION \
            --service-account=$GCP_DEPLOY_SERVICE_ACCOUNT@$GCP_PROJECT_ID.iam.gserviceaccount.com \
            --allow-unauthenticated \
            --cpu=2 \
            --memory=512Mi \
            --timeout=60 \
            --platform managed \
            --region asia-northeast1 \
            --env-vars-file ./.env.yaml \
            --source ./server
