# This workflow will build a Next.js/React project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Next.js

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    strategy:
      matrix:
        node-version: [22.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: ./client
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: ./client/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Format check
        run: |
          npx prettier --check "src/**/*.{ts,tsx,js,jsx,json,css,md}"
          if [ $? -ne 0 ]; then
            echo "❌ Code formatting issues found. Please run 'npx prettier --write .' to fix them."
            exit 1
          fi

      - name: Type check
        run: npx tsc --noEmit

      - name: Build
        run: npm run build